In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import itertools
import statsmodels.api as sm
from matplotlib.ticker import MaxNLocator
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA

# Load data

In [2]:
master_df = pd.read_pickle("master_df.pkl")
master_df

,Date,Adj Close,Close,High,Low,Open,Volume,ETF
5,2007-11-14,382.000000,382.000000,397.000000,364.200012,380.000000,37765.0,ANTE
6,2007-11-15,370.000000,370.000000,381.600006,370.000000,376.000000,19380.0,ANTE
8,2007-11-19,363.399994,363.399994,365.399994,345.600006,355.399994,21095.0,ANTE
9,2007-11-20,345.000000,345.000000,359.399994,327.000000,328.200012,36280.0,ANTE
11,2007-11-23,331.200012,331.200012,368.399994,314.600006,325.000000,39690.0,ANTE
...,...,...,...,...,...,...,...,...
18387217,2025-01-30,50.630001,50.630001,52.270000,48.650002,50.029999,4578200.0,NXT
18387218,2025-01-31,50.419998,50.419998,52.139999,50.395000,51.130001,2389700.0,NXT
18387219,2025-02-03,48.599998,48.599998,49.430000,47.750000,48.320000,2570700.0,NXT
18387220,2025-02-04,49.750000,49.750000,50.340000,47.660000,48.820000,2268300.0,NXT
18387221,2025-02-05,46.970001,46.970001,48.950001,46.700001,48.590000,5242265.0,NXT

# ARIMA orders

In [3]:
etfKey = "VOO"
etfDF = (master_df.loc[master_df["ETF"] == etfKey, ["Date", "Adj Close"]].sort_values("Date").reset_index(drop=True))

# Compute daily log returns:  r_t = ln(P_t / P_{t-1})
etfDF["logRet"] = np.log(etfDF["Adj Close"]).diff()

# Drop the first NaN created by .diff()
etfDF = etfDF.dropna(subset=["logRet"])
etfDF.head()

         Date  Adj Close    logRet
1  2010-09-10  78.074226  0.004530
2  2010-09-13  79.056061  0.012497
3  2010-09-14  79.040749 -0.000194
4  2010-09-15  79.240181  0.002520
5  2010-09-16  79.209480 -0.000388

In [4]:
y = etfDF["logRet"]

# Silence convergence warnings from statsmodels for cleaner output
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)

bestAIC = np.inf
bestP, bestQ = 0, 0

# 36 combinations for p & q
for p in range(6):
    for q in range(6):
        try:
            res = sm.tsa.statespace.SARIMAX(y, order=(p, 0, q), trend="n").fit(disp=False)
            if res.aic < bestAIC:
                print(res.aic, p, q)
                bestAIC, bestP, bestQ = res.aic, p, q
        except (ValueError, np.linalg.LinAlgError):
            # skip non-invertible combos
            continue

print(f"Best ARMA order by AIC: p={bestP}, q={bestQ}  (d=0)")

-22247.586109604857 0 0
-22249.18029875343 0 3
-22254.63615357982 0 5
Best ARMA order by AIC: p=0, q=5  (d=0)

In [5]:
# Fit the chosen model and show diagnostics
arma = sm.tsa.statespace.SARIMAX(y, order=(bestP, 0, bestQ), trend="n").fit(disp=False)

print(arma.summary())

# Ljung-Box test: are residuals white noise?
ljung = sm.stats.acorr_ljungbox(arma.resid, lags=[10, 20], return_df=True)
print("\nLjung-Box p-values:")
print(ljung["lb_pvalue"])

                               SARIMAX Results
==============================================================================
Dep. Variable:                 logRet   No. Observations:                 3495
Model:               SARIMAX(0, 0, 5)   Log Likelihood               11133.318
Date:                Sat, 28 Jun 2025   AIC                         -22254.636
Time:                        10:34:59   BIC                         -22217.682
Sample:                             0   HQIC                        -22241.447
                               - 3495
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ma.L1         -0.0148      0.011     -1.372      0.170      -0.036       0.006
ma.L2          0.0067      0.008      0.856      0.392      -0.009       0.022
ma.L3         -0.0425      0.011     -3.966      0.000      -0.063      -0.021
ma.L4      -9.229e-05      0.012     -0.008      0.994      -0.024       0.024
ma.L5         -0.0519      0.012     -4.356      0.000      -0.075      -0.029
sigma2         0.0001   7.84e-07    127.722      0.000    9.86e-05       0.000
===================================================================================
Ljung-Box (L1) (Q):                   0.06   Jarque-Bera (JB):             95563.38
Prob(Q):                              0.80   Prob(JB):                         0.00
Heteroskedasticity (H):               1.67   Skew:                            -1.90
Prob(H) (two-sided):                  0.00   Kurtosis:                        28.33
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

Ljung-Box p-values:
10    0.978953
20    0.686282
Name: lb_pvalue, dtype: float64

In [6]:
# Forecasting
fc = arma.get_forecast(steps=20)
forecast_mean = fc.predicted_mean
ci = fc.conf_int(alpha=0.05)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

In [7]:
horizon = 20
train = y.iloc[:-horizon]
test  = y.iloc[-horizon:]

# Fit ARMA(p,q) on training data
arma_train = sm.tsa.statespace.SARIMAX(train, order=(bestP, 0, bestQ), trend="n").fit(disp=False)

# Forecast next 20 trading days
fc_res = arma_train.get_forecast(steps=horizon)
fc_mean = fc_res.predicted_mean
ci = fc_res.conf_int(alpha=0.05)

# -----------------------------------------------------------------------------
# Accuracy metrics
# -----------------------------------------------------------------------------
mae  = np.mean(np.abs(test - fc_mean))
rmse = np.sqrt(np.mean((test - fc_mean) ** 2))

# -----------------------------------------------------------------------------
# Plot: actual vs forecast with 95 % confidence band
# -----------------------------------------------------------------------------
fig = plt.figure(figsize=(10, 4))
ax = fig.add_subplot()

# Actual log returns (test set)
ax.plot(test.index, test.values, label="Actual", linewidth=1.2)

# Forecast mean
ax.plot(fc_mean.index, fc_mean.values, linestyle="--", label="Forecast")

# Confidence interval shading
ax.fill_between(fc_mean.index, ci.iloc[:, 0], ci.iloc[:, 1], alpha=0.2)

ax.set_title(f"VOO â€“ 20-day ARMA({bestP},{bestQ}) Forecast on Log Returns\n"
             f"MAE = {mae:.4f},  RMSE = {rmse:.4f}")
ax.set_xlabel("Date")
ax.set_ylabel("Log return")
ax.grid(alpha=0.3)
ax.legend()

plt.tight_layout()
plt.show()

NameError: name 'best_p' is not defined